ENEMIES_CHOSEN_FOR_TRAINING = [1, 4, 6, 7]

MODEL_HIDDEN_LAYERS_SIZES = [64, 64]
MODEL_MIN_WEIGHT = -10
MODEL_MAX_WEIGHT = 10

POP_SIZE = 30
NR_ITERATIONS = 200

INERTIA_INITIAL_WEIGHT = 1
COGNITIVE_WEIGHT = 0.4
SOCIAL_WEIGHT = 0.8

MIN_PARTICLE_SPEED = -3
MAX_PARTICLE_SPEED = 3

THREAD_POOL_SIZE = 3
